<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseService.Domain\CourseService.Domain.csproj" />
    <ProjectReference Include="..\CourseService.Application\CourseService.Application.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Exceptions\Common.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.0" />
    <PackageReference Include="Polly" Version="8.2.0" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

</Project>
